### PR TITLE
Use scope(exit) to close file

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by kubo39** [comment]
Since rawRead raises exception in case emprty file was given.

**Comment by BBasile** [comment]
I don't follow you. Maybe someone else can look at this ?

**Comment by kubo39** [comment]
Ah, sorry, I close this.

**Comment by BBasile** [comment]
To be clear I just suggested to someone else in the dlang-communty organisation to look at this, not to close.
If you can furnish a test case showing to bug you think you fix it's worth reopening.

**Comment by BBasile** [comment]
- make a bug report with some code showing how to reproduce the bug.
- then only make a PR to fix the bug.

The PR was not clear about what it was supposed to fix.

**Comment by BBasile** [comment]
sorry, i see that actually piping is not working (#37). Sorry reopen another pull request but as saud previously make a bug report before.

**Pull request closed without merging**
